include $(POCO_BASE)/build/rules/global

objects = SybaseFoo

target         = SybaseFoo
target_version = 1
target_libs    = PocoDataSybase PocoData PocoFoundation

include $(POCO_BASE)/build/rules/exec
